name: Deploy Portfolio
on:
  push:
    branches:
      - main  # Triggers only on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        run: |
          npm install
          npm run build  # Creates the 'dist' folder

      - name: Deploy to Alwaysdata
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/*"
          target: "/home/sudo-server/www/"
          strip_components: 1  # Uploads contents of dist, not the folder itself
          rm: true  # Cleans the destination before uploading
